//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafenetproModel_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllRules_W_ID
    {
        public AllRules_W_ID()
        {
            this.CategoryToRules = new HashSet<CategoryToRule>();
            this.GroupToRule_W_ID = new HashSet<GroupToRule_W_ID>();
        }
    
        public int ID { get; set; }
        public int RuleOrder { get; set; }
        public int ActionId { get; set; }
        public int RuleTypeId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Rule_Types Rule_Types { get; set; }
        public virtual ICollection<CategoryToRule> CategoryToRules { get; set; }
        public virtual ICollection<GroupToRule_W_ID> GroupToRule_W_ID { get; set; }
    }
}
