//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafenetproModel_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGroup
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
