//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafenetproModel_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.CustomerGroups = new HashSet<CustomerGroup>();
            this.GroupToRule_W_ID = new HashSet<GroupToRule_W_ID>();
        }
    
        public int ID { get; set; }
        public string GroupName { get; set; }
        public string GroupType { get; set; }
    
        public virtual ICollection<CustomerGroup> CustomerGroups { get; set; }
        public virtual ICollection<GroupToRule_W_ID> GroupToRule_W_ID { get; set; }
    }
}
