//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafenetproModel_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int Id { get; set; }
        public int ProductType { get; set; }
        public string ProductName { get; set; }
        public string MonthlyPrice { get; set; }
        public string YearlyPrice { get; set; }
        public Nullable<int> AdditionalLicenseCount { get; set; }
        public string AdditionalLicenseMonthlyPrice { get; set; }
        public string AdditionalLicenseYearlyPrice { get; set; }
        public string SecondMasterMonthlyPrice { get; set; }
        public string SecondmasterYearlyPrice { get; set; }
        public Nullable<int> SettingType { get; set; }
    }
}
