//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafenetproModel_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductToUserChange
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductUserId { get; set; }
        public string OperatingSystem { get; set; }
        public string Location { get; set; }
        public string PrimaryUserName { get; set; }
        public Nullable<int> Settings { get; set; }
        public string PhoneOS { get; set; }
        public string Manufacturer { get; set; }
        public string PrimaryUser { get; set; }
        public string Usage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Change { get; set; }
    }
}
