//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafenetproModel_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule_Types
    {
        public Rule_Types()
        {
            this.Actions = new HashSet<Action>();
            this.AllRules_W_ID = new HashSet<AllRules_W_ID>();
            this.Categories = new HashSet<Category>();
            this.CategoryToRules = new HashSet<CategoryToRule>();
            this.Display_Category = new HashSet<Display_Category>();
            this.GroupToRule_W_ID = new HashSet<GroupToRule_W_ID>();
        }
    
        public int ID { get; set; }
        public string RuleType { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<AllRules_W_ID> AllRules_W_ID { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<CategoryToRule> CategoryToRules { get; set; }
        public virtual ICollection<Display_Category> Display_Category { get; set; }
        public virtual ICollection<GroupToRule_W_ID> GroupToRule_W_ID { get; set; }
    }
}
