//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafenetproModel_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLToDevice
    {
        public string URL { get; set; }
        public Nullable<int> ProductToUser { get; set; }
        public int Id { get; set; }
    
        public virtual ProductToUser ProductToUser1 { get; set; }
        public virtual ProductToUser ProductToUser2 { get; set; }
    }
}
