//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafenetproModel_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string BName { get; set; }
        public string BAddress { get; set; }
        public string BCity { get; set; }
        public string BState { get; set; }
        public string BZip { get; set; }
        public string BPhone { get; set; }
        public string BCellPhone { get; set; }
        public string BFax { get; set; }
        public string BEmailAddress { get; set; }
        public Nullable<int> ProfileType { get; set; }
        public Nullable<int> CardDigits { get; set; }
        public Nullable<bool> BusinessInfo { get; set; }
    
        public virtual User User { get; set; }
    }
}
